### ISSUE TITLE
Send errors to stderr

### ISSUE THREAD

**Issue by savchenko** [rrthomas/rpl#14] opened 2021-11-07 03:07 UTC
Errors are currently sent to `stdout` which precludes from using shell redirects.

Please consider sending them to the correct stream.

**Comment by rrthomas** [comment] 2021-11-07 09:12
What version are you using? As far as I can see, warnings are sent to `stderr`, and have been for some years.

**Comment by savchenko** [comment] 2021-11-07 09:18
```
rpl --version
rpl 1.8.0
```

From `stable` in Debian 11.

**Comment by rrthomas** [comment] 2021-11-07 09:26
Thanks; I think this was fixed in v1.8.1, unfortunately.

**Comment by savchenko** [comment] 2021-11-07 09:33
```sh
$ apt show rpl | grep -i maintainer
Maintainer: Patrick Matthäi <pmatthaei@debian.org>
```

Do you know if backport is planned? 
v1.9.1+ will land in v12, but it is still ~2 years from now.

**Comment by rrthomas** [comment] 2021-11-07 09:33
No idea, sorry. Closing this bug since the problem is not upstream.

**Closed by rrthomas** 2021-11-07 09:33 UTC
